### ISSUE TITLE
Windows 10 Running as admin / non admin yeild different values

### ISSUE THREAD

**Issue by efox29** [jetperch/pyjoulescope#19]
Upgraded to 0.9.3 from 0.9.2 (dirty update - no uninstall). Installer installed in C:\Program Files (x86)\Joulescope and required admin rights on my work computer to install. 

When using, my values were around 300-700uA when they should be < 200uA. 

Downgraded to 0.9.2 (dirty downgrade). Same behavior.

Rebooted machine. Same behaviour.

Uninstalled 0.9.2 and installed 0.9.3. Same behaviour.

Ran 0.9.3 as admin, and the values are < 200uA. 

No admin
![image](https://user-images.githubusercontent.com/304290/101677389-82a7bb00-3a2a-11eb-9830-9dc87d77f2e3.png)

Admin rights
![image](https://user-images.githubusercontent.com/304290/101677590-be428500-3a2a-11eb-8cc6-a973406a7622.png)

**Comment by mliberty1** [comment]
HI @efox29 - This issue is certainly strange.  Judging by the noise levels, I am guessing that the current range (or something else) is different between the two collections.  Could you check that the current ranging is set the same in both cases?  I normally recommend "auto", but just make sure that they are the same.  

Your Joulescope stores config in %LOCALAPPDATA%, so perhaps this is different between the two runs.  I just tried running as admin on my machine, and it seems to pull the same configuration settings.  What do you see?

**Comment by efox29** [comment]
@mliberty1 There are 2 configs one for my domain user account and one for the elevated local user (in their respective %localappdata% directories.

I thought they were both set to auto...

![image](https://user-images.githubusercontent.com/304290/101682127-39a73500-3a31-11eb-9b89-4324ee5112e1.png)

Made it auto, and now I am able to get the correct values.

**Comment by mliberty1** [comment]
Great!  I'm glad that this was something easy...
