### ISSUE TITLE
Python32-bit is not installed

### ISSUE THREAD

**Issue by gavin100200** [jetperch/pyjoulescope#36]
An error occurs when installing joulescope in python3.10.1 32-bit
ERROR: Failed building wheel for pyjoulescope-driver
ERROR: Could not build wheels for pyjoulescope-driver, which is required to install pyproject.toml-based projects

Is it not possible to install 32-bit only 64-bit？

**Comment by mliberty1** [comment]
Hi @gavin100200 - We only officially support 64-bit python on 64-bit operating systems.  We only distribute pre-compiled wheels for 64-bit platforms.  However, you should be able to run 32-bit python on 32-bit operating system.

The error message you posted is definitely truncated.  The actual error would have been displayed previously.  Since we do not distribute 32-bit wheels, this machine has to be configured to build source code, which I suspect is the issue.

Some questions:
1. What operating system are you using?
2. What is the output of `python -VV` (two V)?  You may need to run `python3 -VV` on linux.

**Comment by mliberty1** [comment]
See https://forum.joulescope.com/t/python3-10-1-32-bit-is-not-installed/763

**Comment by mliberty1** [comment]
Will not fix since all major operating systems are now 64-bit.
